themes:
  - name: Light
    applicationBackground: f0f3f9
    textColor: 000000
    operatorBackground: f7f9fc
    numbersBackground: ffffff
    btnEqualTextColor: ffffff
    btnEqualBackground: 0067c0
  - name: Dark
    applicationBackground: 1c2028
    textColor: 2986cc
    operatorBackground: 2d333d
    numbersBackground: 363c47
    btnEqualTextColor: fff fff
    btnEqualBackground: 4cc2ff